#!/usr/bin/env bash
/usr/bin/pkill -9 waybar
/usr/bin/pkill -9 -f workspaces.py
# script to load icons on workspaces (will also reload hyprland and hence restart waybar)
/usr/bin/python3 $HOME/.config/waybar/scripts/workspaces.py debug 2>&1 >$HOME/.cache/workspacer.log &
