services:
  docker-wine-ida:
    image: ghcr.io/nyamisty/docker-wine-ida:7.6sp1
    container_name: docker-ida
    environment:
      - RDP_SERVER=yes
    volumes:
      - $HOME/HACKING:/root/HACKING
    ports:
      - 127.0.0.1:3389:3389
    labels:
      - "DO_NOT_PRUNE=true"
