# Autonotify when a long command has been completed
export AUTO_NOTIFY_THRESHOLD=450
export AUTO_NOTIFY_TITLE="Boss! the command: %command has just finished"
export AUTO_NOTIFY_BODY="Time taken: %elapsed seconds exit code: %exit_code, have a look"
export AUTO_NOTIFY_IGNORE=("htb", "thm", "ipython", "docker" "man","nano","vim","ssh","less","e","openvpn","ping","nc","penelope", 'code', 'crontab', 'watch')
export AUTO_NOTIFY_EXPIRE_TIME=4

# Setting program home directory
export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk/"
export GEM_HOME=~/.ruby/
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh
export ZSH=~/.zsh

# Adding to the PATH
export PATH=$PATH:~/.cargo/bin/
export PATH=$PATH:~/.local/bin/
export PATH=$PATH:~/.local/.scripts/
export PATH=$PATH:~/bin/
export PATH=$PATH:~/.ruby/bin/
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$GOPATH/bin"

export _ZO_DATA_DIR="$ZSH/zoxide"
skip_global_compinit=1

export zi_home="$ZSH/.zi"

export VISUAL=code;
export EDITOR=code;

export HACKING_TOOLS="~/HACKING/Tools"
export HackingSetupScripts="~/HACKING/Tools/Setup-Scripts"

export ZINIT_HOME="$ZSH/zinit/zinit.git"