{{ if .isLinux }}
# DRACULA THEME
[".local/share/themes/Dracula"]
    type = "archive"
    url = "https://github.com/dracula/gtk/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/qt5ct/colors/Dracula.conf"]
    type = "archive-file"
    url = "https://github.com/dracula/qt5/archive/master.zip"
    refreshPeriod = "168h"
    stripComponents = 1
    path = "Dracula.conf"

[".config/qt6ct/colors/Dracula.conf"]
    type = "archive-file"
    url = "https://github.com/dracula/qt5/archive/master.zip"
    refreshPeriod = "168h"
    stripComponents = 1
    path = "Dracula.conf"

[".config/zsh/plugins/zsh-syntax-highlighting/dracula.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/zsh-syntax-highlighting/master/zsh-syntax-highlighting.sh"
    executable = true
    refreshPeriod = "168h"

[".local/bin/raise"]
    type = "archive-file"
    url = '{{ gitHubLatestRelease "lambdachad/raise" | toJson | fromJson | jq ".assets[2].browser_download_url" | first}}'
    executable = true
    refreshPeriod = "168h"
    path = "raise"

[".config/hypr/hyprsplit"]
    type = "git-repo"
    url = "https://github.com/shezdy/hyprsplit"
    branch = "main"

{{- end }}

{{- if (and .isHacking .isLinux) }}
# HACKING

# ## PWN
# ["HACKING/Tools/pwn/libc-database"]
#     type = "git-repo"
#     url = "https://github.com/niklasb/libc-database"
#     branch = "master"
#     refreshPeriod = "250h"

## Cheatsheets
[".local/share/navi/cheats/esp0xdeadbeef"]
    type = "git-repo"
    url = "https://github.com/esp0xdeadbeef/cheat.sheets"
    refreshPeriod = "250h"

{{- end }}
