#!/usr/bin/env bash

rm /tmp/hypr_py/ -rf
# if eww is running, kill it and ensure that only 1 process is running
if [[ $(pidof eww) ]]; then
    pkill -9 eww
    sleep 1
    while [[ $(pidof eww | wc -l) -gt 1 ]]; do
        pkill -9 eww
        sleep 1
    done
fi

## Files and cmd
EWW="eww -c $HOME/.config/eww/"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
echo "NB_MONITORS: ${NB_MONITORS[@]}"
for i in "${!NB_MONITORS[@]}"; do
    ${EWW} open bar$i
    # [[ $i == 0 ]] && ${EWW} open-many sidebar
    sleep 1 # allow some time in order to avoid double bars on monitors
done
