#!/usr/bin/env python3
import sys
import subprocess

def getIcon(self, class_name):
        icon_list = (
            subprocess.check_output(
                ["geticons", "--no-fallbacks", class_name, "-s", "24", "-c", "1"]
            )
            .decode()
            .splitlines()
        )
        icon = icon_list[0] if icon_list else None
        if icon is None:
            lowerClass = class_name.lower()
            icon_list = (
                subprocess.check_output(
                    ["geticons", "--no-fallbacks", lowerClass, "-s", "24", "-c", "1"]
                )
                .decode()
                .splitlines()
            )
            icon = icon_list[0] if icon_list else None
        if icon is None and class_name.strip() != "":
            # send a notification that icon with class_name was not found
            subprocess.Popen(
                [
                    "notify-send",
                    "-u",
                    "critical",
                    "-t",
                    "5000",
                    f"Icon not found for {class_name} manually fix in windowNames.json",
                ]
            )
            icon = self.appgridIcon
        return icon

if __name__ == "__main__":
	getIcon(sys.argv[1])
