---
params:
    regex:
        regex:
            - FLAG{*.}
            - CCSC{*.}
            - picoCTF{*.}
            - CTF{*.}
            - HTB{*.}
            - CHTB{*.}
            - THM{*.}
    brandon:
        top1000: cipheydists::list::english1000
        wordlist: cipheydists::list::english
        stopwords: cipheydists::list::englishStopWords
        threshold: 0.45
