[managers.system]
items = [
    "ags-hyprpanel-git",
    "dart-sass",
    "libevdev",
    "python-evdev",
    "python-filetype",
    "aylurs-gtk-shell-git",
    "libgtop",
    "python-gpustat",
    "swww", # just for hyprpanel to shut up for dependencies
    "caffeine-ng",
]
