[managers.system]
items = [
    "waybar",
    "dart-sass",
    "libevdev",
    "python-evdev",
    "python-filetype",
    "aylurs-gtk-shell",
    "libgtop",
    "python-gpustat",
    "swww", # just for hyprpanel to shut up for dependencies
]

[managers.pip]
items = [
    "svgutils",
]
