[managers.system]
items = [
    "rofi",
    "elephant-bin",
    "elephant-calc-bin",
    "elephant-clipboard-bin",
    "elephant-desktopapplications-bin",
    "elephant-files-bin",
    "elephant-menus-bin",
    "elephant-providerlist-bin",
    "elephant-runner-bin",
    "elephant-symbols-bin",
    "elephant-unicode-bin",
    "elephant-websearch-bin",
    "elephant-windows-bin",
    "walker-bin",
]
