#!/bin/bash
# HAS TO HAVE THE TERMINAL NAME FOR FETCH TO WORK CORRECTLY
# /usr/bin/clear
randomNum=$RANDOM
# if divisible by 2
if [ $((randomNum % 2)) -eq 0 ]; then
    archey4 | lolcat
else
    width=$(tput cols)
    figlet -w $width -f Bloody Evangelospro | lolcat
fi
