#!/bin/bash
# find if there are paramaters such as -r -f or -rf and just remove them
for arg in "$@"; do
    case $arg in
        -r | -f | -rf)
            # Skip these parameters
        ;;
        *)
            # Add non-matching arguments to the new_args array
            new_args+=("$arg")
        ;;
    esac
done

file_loc=$(readlink -f "$new_args")

if echo "$file_loc" | grep -q "SeaDrive"; then
    mv "$file_loc" $HOME/.local/share/Trash/files
    exit 0
else
    trash-put --trash-dir=$HOME/.local/share/Trash "$file_loc"
    exit 0
fi
