pkgs = [
    "spotify-launcher",
    # chaotic-aur/spicetify-cli -> curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
    "aur/spicetify-theme-dracula-git",
    "aur/spotifywm-git",
    "playerctl",
]
