#!/bin/bash

# Swayidle toggle
function toggle {
	if pgrep "swayidle" > /dev/null
	then
		pkill -9 swayidle
		notify-send -r 5556 -u normal " Caffeine Inactive"
	else
		swayidle
		notify-send -r 5556 -u normal "  Caffeine Active"
	fi
}

case $1 in
	toggle)
		toggle
		;;
	*)
		if pgrep "swayidle" > /dev/null
		then
			echo "(image :path \"/home/evangelospro/.config/eww/images/caffeine-active.svg\")"
		else
			echo "(image :path \"/home/evangelospro/.config/eww/images/caffeine-inactive.svg\")"
		fi
		;;
esac
