#!/usr/bin/env bash

function toggle_menu {
    MAIN=$(eww get main_monitor)
    hyprctl keyword blurls "remove,gtk-layer-shell"
    STATE=$(eww windows | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE == '*' ]]; then 
        if [[ $1 == 'powermenu' ]]; then
            hyprctl keyword blurls "remove,gtk-layer-shell"
        fi
        eww close $1$MAIN;
    else
        if [[ $1 == 'powermenu' ]]; then
            hyprctl keyword blurls "gtk-layer-shell"
        fi
        eww open $1$MAIN;
    fi
}

function colorpicker() {
    COLOR=$(hyprpicker -n | grep "#") &&
    wl-copy --trim-newline $COLOR
    notify-send -i color-select-symbolic -a "Color Picker" $(wl-paste)
    echo $COLOR
}


function notifications {
    swaync-client -t
}

function config {
    code $HOME/.config/hypr
}

if [[ $1 == 'pavu'           ]]; then pavucontrol; fi
if [[ $1 == 'brightness'     ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth'      ]]; then blueberry; fi
if [[ $1 == 'powermenu'      ]]; then powermenu; fi
if [[ $1 == 'notifications'  ]]; then notifications; fi
if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
if [[ $1 == 'close_menu'     ]]; then close_menu $2; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'colorpicker'    ]]; then colorpicker; fi
if [[ $1 == 'config'         ]]; then config; fi

if [[ $1 == 'chromium'      ]]; then chromium; fi
if [[ $1 == 'wezterm'       ]]; then wezterm; fi
if [[ $1 == 'file-manager'  ]]; then nautilus; fi
if [[ $1 == 'code'          ]]; then code; fi
if [[ $1 == 'spotify'       ]]; then spotify-client; fi
