#! /bin/bash

history_file=/tmp/dunst-history.json
# create a temporary file to store the history
if [ ! -f "$history_file" ]; then
    touch "$history_file"
fi

collect_history() {
    history=$(dunstctl history)
    echo "$history" > "$history_file"
    echo $(jq -r ".data[]" "$history_file")
}

collect_history
