#!/bin/bash

eww_command="pkill -9 eww; ~/.config/eww/launch_bar"

function bar() {
    # if event is monitoradded or monitorremoved
    if [ ${1:0:12} = "monitoradded" ] || [ ${1:0:14} = "monitorremoved" ]; then
        eval $eww_command
    else
        echo "Unknown event: ${1:0:14}"
    fi
}

socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do bar $line; done