#!/bin/bash

#define icons for workspaces 1-9

targetMonitor=$1
firstMonitor="eDP-1"
secondMonitor="HDMI-A-1"
currMonitor=$firstMonitor
currWorkspace="1"
currClass=""
currIconPath=""
ic=("" "" "" "" "" "" "" "" "")

debug=$2

main () {
  if [[ ${1:0:12} == "focusedmon>>" ]]; then #set focused monitor
    temp=$(echo "$1" | cut -d'>' -f 3)
    currMonitor=$(echo "$temp" | cut -d',' -f 1)
    if [[ $currMonitor == $targetMonitor ]]; then
        currWorkspace=$(echo "$temp" | cut -d',' -f 2)
      if [[ $currMonitor == $secondMonitor ]]; then
        echo "working on monitor HDMI-A-1"
        currWorkspace=$(($currWorkspace % 10))
      fi
    fi
  elif [[ "${1:0:11}" = "workspace>>" ]] && [[ $currMonitor == $targetMonitor ]]; then
    #set focused workspace
    currWorkspace=$(echo "$1" | cut -d'>' -f 3)
    if [[ $currMonitor == $secondMonitor ]]; then
      currWorkspace=$(($currWorkspace % 10))
    fi
    activeWindow=$(hyprctl activewindow)
    currClass=$(echo "$activeWindow" | grep "class: " | awk '{print $2}')
    currIconPath=$(geticons --no-fallbacks "$currClass" -s 24 -c 1| head -n 1)
    if [[ $currIconPath != "" ]]; then
      ic[$currWorkspace]=$currIconPath
    fi
  # elif [[ "${1:0:14}" = "activewindow>>" ]] && [[ $currMonitor = $targetMonitor ]]; then #set focused workspace
  #   temp=$(echo "$1" | cut -d'>' -f 3)
  #   currClass=$(echo "$temp" | cut -d',' -f 1)
  #   if [[ $currClass != "" ]]; then
  #     currIconPath=$(geticons --no-fallbacks "$currClass" -s 24 -c 1| head -n 1)
  #   fi
  #   # if it isn't null try with lowercase
  #   if [[ $currIconPath == "" ]]; then
  #     currClass=$(echo "$currClass" | tr '[:upper:]' '[:lower:]')
  #     currIconPath=$(geticons --no-fallbacks "$currClass" -s 24 -c 1 | head -n 1)
  #   fi
  #   if [[ $currIconPath != "" ]]; then
  #     ic[$currWorkspace]=$currIconPath
  #   fi
  fi
  if [[ $debug == "debug" ]]; then
    echo "focusedmon>>$currMonitor"
    echo "workspace>>$currWorkspace"
    echo "activewindow>>$currClass"
    echo "icon>>$currIconPath"
  fi

buttons=""
# output eww widget
for num in {1..9}; do
  # echo "num: $num icon: ${ic[$num]}"
  if [[ ${ic[$num]} == "" ]]; then
    ic[$num]=$(geticons --no-fallbacks "appgrid" -s 24 -c 1 | head -n 1)
  fi
  if [[ $num == $currWorkspace ]]; then
    buttons+="(button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace $num\'\" :onrightclick \"hyprctl dispatch workspace $num && $HOME/.config/hypr/scripts/default_app\" :class \"active-workspace\" (image :path \"${ic[$num]}\" :image-width \"36\" :image-height \"36\" :tooltip \"Workspace $num\"))"
  else
    buttons+="(button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace $num\'\" :onrightclick \"hyprctl dispatch workspace $num && $HOME/.config/hypr/scripts/default_app\" (image :path \"${ic[$num]}\" :image-width \"24\" :image-height \"24\" :tooltip \"Workspace $num\"))"
  fi
done
result="(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
              $buttons \
          ) \
        )"
if [[ $debug != "debug" ]]; then
  echo "$result"
fi
}

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
  main "$event"
done