#!/bin/bash

# Get brightness
get_brightness() {
    max=$(brightnessctl m)
    current=$(brightnessctl g)
    percent=$(echo "scale=2; $current / $max * 100" | bc)
	echo "$percent"
}

# Increase brightness
inc_brightness() {
	brightnessctl set 5%+
}

# Decrease brightness
dec_brightness() {
	brightnessctl set 5%-
}

# Set brightness
set_brightness() {
    brightnessctl s "$2"
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_brightness
elif [[ "$1" == "--set" ]]; then
	set_brightness
elif [[ "$1" == "--inc" ]]; then
	inc_brightness
elif [[ "$1" == "--dec" ]]; then
	dec_brightness
else
	get_brightness
fi
