#!/usr/bin/env bash

getCapsLockIcon() {
    # use material design icons
    locked_icon="C"
    unlocked_icon="c"
    xset q | grep -q 'Caps Lock:   on' && echo -n $lock_icon || echo -n $unlocked_icon
}

getNumLockIcon() {
    # use material design icons
    locked_icon="N"
    unlocked_icon="n"
    xset q | grep -q 'Num Lock:    on' && echo -n $lock_icon || echo -n $unlocked_icon
}

getShortName() {
    if [[ $1 =~ English.* ]]; then
        echo -n 'EN '
    elif [[ $1 =~ Greek.* ]]; then
        echo -n 'GR '
    else
        echo -n '?? '
    fi
}

# initial value to display
layoutLine=$(hyprctl devices | grep keymap | tail --lines 1)
getShortName ${layoutLine#*:}
getCapsLockIcon
getNumLockIcon
