#!/bin/sh

EWW_BIN="eww -c $HOME/.config/eww"
LOCK_DIR="$HOME/.cache/"

closeAll() {
    ${EWW_BIN} close system audio_ctl calendar
}

notifications()
{
    LOCK_FILE="$LOCK_DIR/eww-notification.lock"

    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} open notification
    else
        ${EWW_BIN} close notification
        \rm "$LOCK_FILE"
    fi
}



if [ "$1" = "--notifs" ]; then
    notifications
else
    echo "Usage: $0 --notifs"
fi
