#!/bin/bash

# all in Mb/s
IF="wlan0"
if [ -z "$IF" ]; then
        IF=`ls -1 /sys/class/net/ | head -1`
fi
RXPREV=-1
TXPREV=-1
echo "Listening $IF..."
while 
        RX=`cat /sys/class/net/${IF}/statistics/rx_bytes`
        TX=`cat /sys/class/net/${IF}/statistics/tx_bytes`
        if [ $RXPREV -ne -1 ] ; then
                let BWRX=$RX-$RXPREV
                let BWTX=$TX-$TXPREV
                echo "Received: $BWRX B/s    Sent: $BWTX B/s"
        fi
        RXPREV=$RX
        TXPREV=$TX
        sleep 1
done


# if the first argument is --speeds, then print the speeds
if [ "$1" = "--speeds" ]; then
    echo -n " "
    if [ $download_wifi -gt 0 ]; then
        echo -n "直"
        echo -n " ${download_wifi}"
    fi
    if [ $upload_wifi -gt 0 ]; then
        echo -n " ${upload_wifi} "
    fi
    if [ $download_eth -gt 0 ]; then
        echo -n ""
        echo -n " ${download_eth}"
    fi
    if [ $upload_eth -gt 0 ]; then
        echo -n " ${upload_eth} "
    fi
elif [ "$1" = "--upload" ]; then
    echo -n "  直 ${upload_wifi}  ${upload_eth}"
elif [ "$1" = "--download" ]; then
    echo -n "  直 ${download_wifi}   ${download_eth}"
fi
