[[profile]]
name = "laptop"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
[[profile.output]]
# search for a matching serial number and model by full text comparison
search = ["m=0x004D", "s=", "v=Najing CEC Panda FPD Technology CO. ltd"]
enable = true
mode = "1920x1080@144"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "home"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
[[profile.output]]
# search for a matching serial number and model by full text comparison
search = ["m=0x004D", "s=", "v=Najing CEC Panda FPD Technology CO. ltd"]enable = true
mode = "1920x1080@144"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
# search for a matching serial number and model by full text comparison
search = ["m=0x004D", "s=", "v=Najing CEC Panda FPD Technology CO. ltd"]
enable = true
mode = "1920x1080@144"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
