#!/usr/bin/env bash
set -e

if ! pacman -Qs base-devel >/dev/null 2>&1; then
    sudo pacman -Sy --noconfirm base-devel
fi

# Insall python-pip, pypy and uv
if ! pacman -Qs python-pip >/dev/null 2>&1; then
    sudo pacman -S --noconfirm python-pip
fi

if ! pacman -Qs pypy3 >/dev/null 2>&1; then
    sudo pacman -S --noconfirm pypy3
fi

if ! pypy3 -m pip --version; then
    pypy3 -m ensurepip
fi

if ! pacman -Qs uv >/dev/null 2>&1; then
    sudo pacman -S --noconfirm uv
fi

# COPY SYSTEM CONFIGURATIONS
rebos api echo info "Copying system configurations (/etc, /usr, /var)"
sudo cp -r ~/.config/system/* /

# SYNC SYSTEM REPOS
rebos api echo info "Syncing system repos"
sudo pacman -Sy --noconfirm
