#!/usr/bin/env bash

if pacman -Qs virt-manager >/dev/null 2>&1; then
    rebos api echo info "Setting up libvirt"
    sudo usermod -aG libvirt $USER
    sudo usermod -aG kvm $USER
    sudo usermod -aG video $USER

    sudo systemctl enable libvirtd.service --now

    sudo virsh net-autostart default >/dev/null
fi

# COPY SYSTEM CONFIGURATIONS

rebos api echo info "Copying system configurations"
sudo cp -r ~/.local/share/chezmoi/confs/etc/* /etc/
sudo cp -r ~/.local/share/chezmoi/confs/usr/* /usr/

# ENABLE SERVICES
rebos api echo info "Enabling services"
sudo systemctl enable --now NetworkManager.service
sudo systemctl enable --now bluetooth.service

# UPDATE using the update binary in ~/.local/bin
rebos api echo info "Updating all packages and installing any source-only packages"
update

rebos api echo sucess "Please reboot to ensure everything was sucessfully applied"
