#!/usr/bin/env bash
set -e

if ! pacman -Qs base-devel >/dev/null 2>&1; then
    sudo pacman -Sy --noconfirm base-devel
fi

# Install chaotic aur
if ! pacman -Qs chaotic-keyring >/dev/null 2>&1; then
    echo "Setting up chaotic aur"
    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB
    sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
fi

# Insall python-pip, pypy and pipx
if ! pacman -Qs python-pip >/dev/null 2>&1; then
    sudo pacman -S --noconfirm python-pip
fi

if ! pacman -Qs pypy3 >/dev/null 2>&1; then
    sudo pacman -S --noconfirm pypy3
    pypy3 -m ensurepip
fi

if ! pacman -Qs pipx >/dev/null 2>&1; then
    sudo pacman -S --noconfirm pipx
fi

# COPY SYSTEM CONFIGURATIONS
rebos api echo info "Copying system configurations (/etc, /usr, /var)"
sudo cp -r ~/.local/share/chezmoi/confs/* /
