#!/usr/bin/env bash
set -e

if pacman -Qs virt-manager >/dev/null 2>&1; then
    rebos api echo info "Setting up libvirt"
    sudo usermod -aG libvirt $USER
    sudo usermod -aG kvm $USER
    sudo usermod -aG video $USER

    sudo systemctl enable libvirtd.service --now

    sudo virsh net-autostart default >/dev/null
fi

# COPY SYSTEM CONFIGURATIONS
rebos api echo info "Copying system configurations"
sudo cp -r ~/.local/share/chezmoi/confs/* /

# UPDATE using the update binary in ~/.local/bin
rebos api echo info "Updating all packages and installing any source-only packages"
~/.local/bin/update

# Change shell to zsh
# check if zsh is installed and that it is not the users default shell
if [[ $SHELL == "/bin/zsh" ]]; then
    rebos api echo info "zsh is already the default shell not changing"
else
    if ! pacman -Qs zsh >/dev/null 2>&1; then
        rebos api echo error "zsh is not installed..."
    else
        rebos api echo info "Changing shell to zsh"
        chsh -s /bin/zsh
    fi
fi

rebos api echo success "Please reboot to ensure everything was successfully applied"
