[managers.system]
items = [
  "qemu-full",
  "virt-manager",
  "virt-viewer",
  "qqx",
]


[managers.systemd-system]
items = [
    "libvirtd"
]

[managers.groups]
items = [
    "libvirt",
    "kvm"
]
