#!/bin/bash

MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
if [[ ${#MONITORS[@]} -gt 1 ]]; then
    FOCUS=($(hyprctl monitors -j | jq -r '.[] | .focused'))
    for i in "${!FOCUS[@]}"; do
        if [[ ${FOCUS[i]} == 'true' ]]; then
            eww update main_monitor=$i
        fi
    done
fi