[managers.system]
items = [
    "aur/jadx-gui-desktop",
    "aur/python-frida",
    "android-udev",
    "chaotic-aur/android-emulator",
    "chaotic-aur/android-sdk-cmdline-tools-latest",
    "chaotic-aur/android-sdk-platform-tools",
    "android-tools",
    "chaotic-aur/android-studio"
]
