[managers.system]
items = [
    "android-udev",
    "android-emulator",
    "android-sdk-cmdline-tools-latest",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-tools",
    # "android-studio"
]
