#!/bin/bash

# [body] markup:
# https://specifications.freedesktop.org/notification-spec/latest/ar01s04.html

# swaync-client -C
# make a lock file, if it exists then we close the script, if not we create it
if [ -f /tmp/swaync.lock ]; then
    swaync-client -cp
    rm /tmp/swaync.lock
else
    touch /tmp/swaync.lock
    swaync-client --reload-config
    swaync-client -rs
    swaync-client -op
fi

# -u critical
# -t 5000
# -i $(rngicon)
# notify-send -i $(rngicon) hi there
# notify-send -i $(rngicon) "Test icon notification" "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut mauris quis ante bibendum gravida. Sed mollis neque felis, quis rutrum risus porttitor vel. Duis finibus lorem nec massa lacinia, quis vehicula est ultricies. Suspendisse consectetur orci a quam fringilla, id malesuada quam posuere. Vestibulum non ipsum consequat, venenatis turpis nec, viverra mi. Sed bibendum odio vel augue luctus congue."
# notify-send "Test noicon notification" "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut mauris quis ante bibendum ..."
# notify-send -u critical "Test critical notification" "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut mauris quis ante bibendum ..."
# notify-send -i /home/evangelospro/Pictures/test.jpg hi "<img src=\"/home/evangelospro/Pictures/test2.jpg\"/> hi there testing..."
