imports = [
    "applications/browser",
    "applications/communications",
    "applications/editors",
    "applications/image",
    "applications/music",
    "applications/note_taking",
    "applications/office",
    "applications/recording",
    "applications/screenshotting",
    "applications/terminal",
    "applications/video",
]
