pkg_managers.system.pkgs = [
    "linux-g14",
    "linux-g14-headers",
    "intel-compute-runtime",
    "vulkan-intel",
    "power-profiles-daemon",
    "aur/asusctl-git",
    "aur/supergfxctl-git",
    "aur/rog-control-center",
]
