[managers.system]
items = [
    "ntpsec", # network time (idk why arch doesn't have this by default...)
    "tzupdate", # update timezones based on geoip
    "mkinitcpio-numlock", # enable numlock on boot
    "grub-hook", # update grub on kernel update (idk why arch doesn't have this in the grub package itself...)
    "intel-ucode",
    "amd-ucode",
    "mesa-utils",
    "fwupd",
    "e2fsprogs",
    "efibootmgr",
    "linux-atm",
    "linux-firmware",
    "linux-firmware-marvell",
    "binder_linux-dkms",
    "lld",
    "llvm",
    "gvfs",
    "udisks2",
    "parted",
    "zip",
    "unzip",
    "clang",
    "gcc",
    "alsa-utils",
    "b43-fwcutter",
    "base",
    "bind",
    "brltty",
    "btrfs-progs",
    "cryptsetup",
    "darkhttpd",
    "ddrescue",
    "dhclient",
    "dhcpcd",
    "diffutils",
    "dmidecode",
    "dmraid",
    "dosfstools",
    "edk2-shell",
    "espeakup",
    "ethtool",
    "exfatprogs",
    "f2fs-tools",
    "fatresize",
    "fsarchiver",
    "gnu-netcat",
    "gpart",
    "gpm",
    "gptfdisk",
    "grub",
    "hdparm",
    "hyperv",
    "irssi",
    "iw",
    "iwd",
    "jfsutils",
    "jgmenu",
    "less",
    "lftp",
    "libfido2",
    "libusb-compat",
    "livecd-sounds",
    "lsscsi",
    "lvm2",
    "man-db",
    "os-prober",
    "inetutils",
    "preload",
    "base-devel",
    "appmenu-gtk-module",
    "parallel",
    "rsync",
    "sshpass",
]
