[managers.system]
items = [
    "docker",
    "docker-buildx",
    "docker-rootless-extras",
    "docker-compose",
    "fuse-overlayfs",
]

[managers.systemd-system]
items = [
    "docker.socket", # avoid docker.service as that starts the daemon, while socket just listens until docker is needed on demand
]
