[managers.system]
items = [
    "nemo",
    "nemo-fileroller",
    "nemo-compare",
    "nemo-preview",
    # "nemo-terminal",
    "nemo-image-converter",
    "nemo-media-columns",
    "lf",
    "fd",
    "ouch",
]
