[managers.system]
items = [
    "noto-fonts",
    "noto-fonts-emoji",
    "noto-fonts-extra",
    "noto-fonts-cjk",
    "otf-font-awesome",
    "figlet-fonts-extra",
    "ttf-material-design-icons-extended",
    "tesseract",
    "tesseract-data-eng"
]
