[managers.system]
items = [
    "gdb",
    "ninja",
    "gcc",
    "cmake",
    "meson",
    "libxcb",
    "xcb-proto",
    "xcb-util",
    "xcb-util-keysyms",
    "libxfixes",
    "libx11",
    "libxcomposite",
    "xorg-xinput",
    "libxrender",
    "pixman",
    "wayland-protocols",
    "cairo",
    "pango",
    "seatd",
    "libxkbcommon",
    "xcb-util-wm",
    "xorg-xwayland",
    "libinput",
    "libliftoff",
    "libdisplay-info",
    "cpio",
    "tomlplusplus",
    "xcur2png",
    "aur/hyprlang-git",
    "aur/hyprwayland-scanner-git"
]
