[managers.system]
items = [
    "rebos-git",
    ## Arch specific start
    "pacman-static",
    "rate-mirrors-bin",
    "pacman-cleanup-hook",
    "reboot-arch-btw",
    "downgrade",
    ## Arch specific end
]
