[managers.system]
items = [
    "zsh",
    "vivid",
    "direnv",
    "curl",
    "curlie",
    "fcp-bin",
    "plocate",
    "wget",
    "progress",
    "trash-cli",
    "thefuck",
    "zoxide",
    "onefetch",
    "fastfetch",
    "ack",
    "figlet",
    "c-lolcat",
    "bat",
    "lsd",
    "mcfly",
    "doggo-bin",
    "tgpt-bin", # AI copilot with no api keys
    "atuin",
    "unzip",
    "glow",
    "tealdeer",
    "ffmpeg",
    "btop",
    "geticons-git",
    "moreutils",
    # "batify",
    "wev",
    "navi"
]
