[managers.system]
items = [
    "bash",
    "bash-completion",
    "zsh",
    "oh-my-posh-bin",
    "vivid",
    "direnv",
    "curl",
    "curlie",
    "fcp-bin",
    "plocate",
    "wget",
    "progress",
    "trash-cli",
    "pay-respects-bin",
    "zoxide",
    "onefetch",
    "fastfetch",
    "ack",
    "figlet",
    "c-lolcat",
    "bat",
    "bat-extras",
    "lsd",
    "dua-cli",
    "doggo-bin",
    "atuin",
    "glow",
    "tealdeer",
    "bottom",
    "procs",
    "geticons-git",
    "moreutils",
    "wev",
    "navi",
    "cmatrix",
    "cava",
    "hyperfine",
    "duf",
    "cyme",
    "libtree-bin",
]

[managers.uvx]
items = [
    "ffmpeg-progress-yield"
]
