[managers.system]
items = [
    "zsh",
    "vivid",
    "direnv",
    "curl",
    "curlie",
    "fcp-bin",
    "plocate",
    "wget",
    "progress",
    "trash-cli",
    "thefuck",
    "zoxide",
    "onefetch",
    "fastfetch",
    "ack",
    "figlet",
    "c-lolcat",
    "bat",
    "bat-extras",
    "lsd",
    "doggo-bin",
    "atuin",
    "unzip",
    "glow",
    "tealdeer",
    "btop",
    "procs",
    "geticons",
    "moreutils",
    "wev",
    "navi",
    "cmatrix",
    "cava",
]
