pkg_managers.system.pkgs = [
    "zsh",
    "vivid",
    "direnv",
    "curl",
    "curlie",
    "aur/fcp-bin",
    "plocate",
    "wget",
    "progress",
    "trash-cli",
    "thefuck",
    "zoxide",
    "fastfetch",
    "ack",
    "figlet",
    "chaotic-aur/c-lolcat",
    "bat",
    "lsd",
    "mcfly",
    "aur/doggo-bin",
    "aur/tgpt-bin", # AI copilot with no api keys
    "atuin",
    "unzip",
    "glow",
    "tealdeer",
    "ffmpeg",
    "btop",
    "aur/geticons",
    "moreutils",
    # "aur/batify",
    "wev",
    "navi"
]
