# systemd-user

sync = "systemctl --user daemon-reload"
add = "systemctl --user enable --now #:?"
remove = "systemctl --user disable --now #:?"

plural_name = "systemd-user"
hook_name = "systemd-user"

[config]
many_args = true
arg_sep = " "
