# system

# skip tests not needed make it go Brrr
add = "paru --needed -S --mflags '--nocheck' --noconfirm #:?"
remove = "paru -Rns #:?"
sync = "paru -Syy"
upgrade = "paru -Syu"

plural_name = "system packages"

[config]
many_args = true
