# system

# skip tests not needed make it go Brrr
add = "paru --needed -S --mflags '--nocheck' --overwrite '*' --noconfirm #:?"
remove = "paru -Rns #:?"
sync = "paru -Syy"
upgrade = "paru -Su --devel"

plural_name = "system-packages"
hook_name = "system-packages"

[config]
many_args = true
arg_sep = " "
