imports = [
    "core_packages",
    "applications",
    "programming",
    "toolkits",
    "utils",
    "chaotic-aur",
    "docker",
    "dotfiles",
    "file_managment",
    "fonts",
    "git",
    "hyprland",
    "packaging",
    "rdp",
    "shell",
    "themes",
    "vpns",
    "xdg",
    "downloaders",
]

[managers.systemd-system]
items = [
    "plocate-updatedb.timer",
]

[managers.systemd-user]
items = [
    "docker",
    "gnome-keyring-daemon",
    "battery_notifier",
    "polkit-gnome",
    "avizo",
    "swaync",
    "idle",
    "wl-clip-persist",
    "wl-paste",
    "battery_notifier",
    "waybar",
    # "waybar-icons",
    # "blueman-applet",
    # "nm-applet",
    # "usbguard-applet",
    # "udiskie",
]

[managers.groups]
items = [
    "seat",
]
