imports = [
    "core_packages",
    "applications",
    "programming",
    "toolkits",
    "utils",
    "chaotic-aur",
    "docker",
    "dotfiles",
    "file_managment",
    "fonts",
    "git",
    "hyprland",
    "packaging",
    "rdp",
    "shell",
    "themes",
    "vpns",
    "xdg",
    "downloaders",
]

[managers.systemd]
items = [
    "docker",
]
