imports = [
    "core_packages",
    "applications",
    "programming",
    "toolkits",
    "utils",
    "chaotic-aur",
    "docker",
    "dotfiles",
    "file_managment",
    "fonts",
    "git",
    "hyprland",
    "packaging",
    "rdp",
    "shell",
    "themes",
    "vpns",
    "xdg",
    "downloaders",
]

[managers.systemd-user]
items = [
    "docker",
    "polkit-gnome-authentication-agent-1",
    "gnome-keyring-daemon"
]
