[managers.system]
items = [
    "pycdc-git",
    "python-pyshark",
    "volatility3-git",
    # aur/python2-volatility-git,
    "foremost",
    "python-oletools",
    "powershell",
]

[managers.pipx]
items = [
    "stringcheese",
]
