[managers.system]
items = [
    "pycdc-git",
    "python-pyshark",
    "volatility3-git",
    # "python2-volatility-git",
    "foremost",
    "python-oletools",
    "powershell",
    "binwalk",
]

[managers.pipx]
items = [
    "stringcheese",
]
