[managers.system]
items = [
    "aur/pycdc-git",
    "aur/python-pyshark",
    "aur/volatility3-git",
    # aur/python2-volatility-git,
    "foremost",
    "aur/python-oletools",
    "chaotic-aur/powershell",
]

[managers.pipx]
items = [
    "stringcheese",
]
