[managers.system]
items = [
    "pycdc-git",
    "python-pyshark",
    "python-pypykatz",
    "volatility3-git",
    "foremost",
    "python-oletools",
    "powershell-bin",
    "binwalk",
]

[managers.uvx]
items = [
    # "stringcheese",

]
