[managers.system]
items = [
    "pycdc-git",
    "python-pyshark",
    "volatility3",
    "foremost",
    "python-oletools",
    "powershell-bin",
    "binwalk",
]

[managers.uvx]
items = [
    "stringcheese",

]

[managers.pip]
items = [
    "git+https://github.com/Hedroed/png-parser",
]
