[managers.system]
items = [
    "pycdc-git",
    "python-pyshark",
    "volatility3-git",
    # "python2-volatility-git",
    "foremost",
    "python-oletools",
    "powershell-bin",
    "binwalk",
]

[managers.pipx]
items = [
    "stringcheese",

]

[managers.pip]
items = [
    "git+https://github.com/Hedroed/png-parser",
]
