[managers.system]
items = [
    "checksec",
    "gdb",
    "pwndbg",
    "gef",
    "strace",
    "python-typing_extensions",
    "python-tabulate",
    "python-pwntools",
    "python-pwnscripts",
    "ropper",
    "ropgadget",
]
