[managers.system]
items = [
    "python-z3-solver",
    "ghidra",
    "binaryninja-free",
    "cutter",
    "rz-ghidra",
    "rz-cutter",
    "dotnet-runtime-6.0",
    # "avaloniailspy",
    "jd-gui-bin",
    "recaf-bin",
]
