pkg_managers.system.pkgs = [
    "python-z3-solver",
    "python-claripy",
    # "aur/python-angr-git",
    "ghidra",
    "cutter",
    "rz-ghidra",
    "rz-cutter",
    "dotnet-runtime-6.0",
    "aur/jd-gui",
    "aur/recaf-bin"
]
