[managers.system]
items = [
    "python-z3-solver",
    "ghidra",
    "cutter",
    "rz-ghidra",
    "rz-cutter",
    "dotnet-runtime-6.0",
    # "avaloniailspy",
    "jd-gui-bin",
    "recaf-bin",
]

[managers.pypy]
items = [
    "ipython",
    "z3-solver",
    "claripy",
    "angr",
]
