[managers.system]
items = [
    "python-z3-solver",
    "python-claripy",
    # "python-angr-git",
    "ghidra",
    "cutter",
    "rz-ghidra",
    "rz-cutter",
    "dotnet-runtime-6.0",
    "jd-gui",
    "recaf-bin"
]
