[managers.system]
items = [
    "nodejs-localtunnel",
    "python-beautifulsoup4",
    "python-flask",
    "wpscan",
    "joomscan",
    "sqlmap",
    "python-pyjwt",
    "python-websockets",
    "python-httpx",
]

[managers.pip]
items = [
    "requestrepo",
]

[managers.pipx]
items = [
    "updog",
    "scoutsuite",
]
