[managers.system]
items = [
    "feroxbuster-bin",
    "ffuf-bin",
    "python-beautifulsoup4",
    "python-flask",
    "wpscan",
    "joomscan",
    "sqlmap",
    "python-pyjwt",
    "python-websockets",
    "python-httpx",
    "grpcurl-bin",
    "socat",
]

[managers.pip]
items = [
    "requestrepo",
    "flask-unsign",
    "wconsole_extractor",
]

[managers.pipx]
items = [
    "updog",
    "scoutsuite",
]
