[managers.system]
items = [
    "nodejs-localtunnel",
    "python-beautifulsoup4",
    "python-flask",
    "wpscan",
    "joomscan",
    "sqlmap",
]

[managers.pipx]
items = [
    "updog",
    "scoutsuite",
]
