[managers.system]
items = [
]

[managers.uvx]
items = [
    "git+https://github.com/Pennyw0rth/NetExec",
    "git+https://github.com/cddmp/enum4linux-ng",
    "impacket",
    "bloodyad",
    "certipy",
]
