[managers.system]
items = [
    "python-pycryptodome",
    "python-pycryptodomex",
    "sagemath",
    "python-numpy",
    # "rsactftool-git", TODO: find better installation method
    "python-randcrack-git",
]
