[managers.system]
items = [
    "stegsolve",
    # "steghide", TODO: Check https://aur.archlinux.org/packages/steghide for when libjpeg -> libjpeg.so
    "stegseek",
    "perl-image-exiftool",
    "sonic-visualiser",
]

[managers.gem]
items = [
    "zsteg"
]
