#!/bin/bash

debug=$1

log() {
    if [[ $debug == "debug" ]]; then
        echo $1
    else
        notify-send "$1"
    fi
}

function handle {
    log "handling $1"
    if [[ ${1:0:13} == "fullscreen>>0" ]]; then
        swayidle
        msg="fullscreen>>0 -> caffeine deactivated"
        log $msg
        elif [[ ${1:0:13} == "fullscreen>>1" ]]; then
        pkill -9 swayidle
        msg="fullscreen>>1 -> caffeine activated"
        log $msg
    fi
}

socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do
    handle $line;
done
