#!/usr/bin/env bash
WORKSPACES_COUNT_PER_MONITOR=10
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <workspace> [action](movewindow|change) [workspace](1-$WORKSPACES_COUNT_PER_MONITOR)"
    exit 1
fi

activeMonitorNumber=$(hyprctl monitors -j | jaq -r '.[] | select(.focused == true) | .id')
if [ -z "$activeMonitorNumber" ]; then
    echo "No active monitor found"
    exit 1
fi

# actual workspace number is as activeMonitorNumber * WORKSPACES_COUNT_PER_MONITOR + workspaceNumber
action="$1"
workspaceNumber="$2"
echo "activeMonitorNumber: $activeMonitorNumber"
echo "workspaceNumber: $workspaceNumber"
echo "action: $action"
workspaceNumber=$((activeMonitorNumber * WORKSPACES_COUNT_PER_MONITOR + workspaceNumber))
if [ "$action" == "movewindow" ]; then
    hyprctl dispatch movetoworkspace "$workspaceNumber"
    exit 0
elif [ "$action" == "change" ]; then
    hyprctl dispatch workspace "$workspaceNumber"
    exit 0
fi
