#!/bin/bash

function handle {
  if [[ ${1:0:13} == "fullscreen>>1" ]]; then
    caffeinated &
  elif [[ ${1:0:13} == "fullscreen>>0" ]]; then
    pkill -9 caffeinated
  fi
}

socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; 
handle $line;
done