#!/usr/bin/env bash
shopt -s extglob

monitors_file=$HOME/.config/hypr/monitors.conf
common_path=$HOME/.config/hypr/monitors

# find the current mode by reading the symlink and replacing the common path and .conf
current_mode=$(readlink $monitors_file | sed "s|$common_path/||;s|.conf$||")
echo "Current mode: $current_mode"

options=("Builtin" "Extend" "Duplicate")
# append a (current) to the current mode (case insensitive)
for i in "${!options[@]}"; do
    echo "${options[$i],,} == ${current_mode,,}"
    if [[ "${options[$i],,}" == "${current_mode,,}" ]]; then
        options[$i]="${options[$i]} (current)"
    fi
done
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -p "Select a mode")

# Run the appropriate script
if [ -z "$choice" ]; then
    echo "No choice made, exiting"
    exit 0
fi
case $choice in
"Builtin"|"Builtin (current)")
    ln -nsf $common_path/builtin.conf $monitors_file
    ;;
"Extend"|"Extend (current)")
    hyprctl
    ln -nsf $common_path/extend.conf $monitors_file
    ;;
"Duplicate"|"Duplicate (current)")
    ln -nsf $common_path/duplicate.conf $monitors_file
    ;;
*)
    echo "Invalid choice: $choice, exiting"
    exit 1
    ;;
esac

hyprctl reload
