#!/usr/bin/env bash
WORKSPACES_COUNT_PER_MONITOR=10
if [ -z "$1" ]; then
    echo "Usage: $0 <workspace/movetoworkspace> [workspace]"
    exit 1
fi

activeMonitorNumber=$(hyprctl monitors -j | jaq -r '.[] | select(.focused == true) | .id')
if [ -z "$activeMonitorNumber" ]; then
    echo "No active monitor found"
    exit 1
fi

if [ "$1" == "workspace" ]; then
    if [ -z "$2" ]; then
        echo "Usage: $0 workspace <workspace>"
        exit 1
    fi
    # actual workspace number is as activeMonitorNumber * WORKSPACES_COUNT_PER_MONITOR + workspaceNumber
    workspaceNumber="$2"
    workspaceNumber=$((activeMonitorNumber * WORKSPACES_COUNT_PER_MONITOR + workspaceNumber))
    hyprctl dispatch workspace "$workspaceNumber"
elif [ "$1" == "movetoworkspace" ]; then
    if [ -z "$2" ]; then
        echo "Usage: $0 movetoworkspace <workspace>"
        exit 1
    fi
    workspaceNumber="$2"
    workspaceNumber=$((activeMonitorNumber * WORKSPACES_COUNT_PER_MONITOR + workspaceNumber))
    hyprctl dispatch movetoworkspace "$workspaceNumber"
else
    echo "Usage: $0 <workspace/movetoworkspace> [workspace]"
    exit 1
fi
