#!/bin/bash

# Define the options for the Rofi menu
options=("Extend Monitors
Duplicate Monitors")
choice=$(printf '%s

' "${options[@]}" | rofi -dmenu -i -p "Monitor configuration")

# Run the appropriate script
case $choice in
"Extend Monitors")
    cp $HOME/.config/hypr/monitors_extend.conf $HOME/.config/hypr/monitors.conf
    reload-hyprland
    ;;
"Duplicate Monitors")
    cp $HOME/.config/hypr/monitors_duplicate.conf $HOME/.config/hypr/monitors.conf
    reload-hyprland
    ;;
esac
