#!/bin/bash
TERM="wezterm"          #Tag 1
BROWSER="chromium"      #Tag 2
FILE="dolphin"          #Tag 4
DEV="code"              #Tag 4

#Lookup Focused tag
TAG=$(hyprctl monitors | grep -B 4 "focused: yes" | awk 'NR==2 {print $1}' RS='(' FS=')')

#Executes application based on number of focused tag
case "$TAG" in 
  1) $TERM &> /dev/null ;;
  2) $BROWSER &> /dev/null ;;
  3) $SANDBOX &> /dev/null ;;
  4) $DEV &> /dev/null ;;
esac
