#!/bin/bash

clean(){
    # reapply the background
    pkill -9 swaybg && swaybg -o \* -i ~/Pictures/backgrounds/background.png -m fill &
    if [["$(pidof amadeus.x86 | wc -w)" eq 0]]; then
        # reload eww
        # ~/.local/bin/ewwLaunch
    fi
    hyprctl reload
}

# Define the options for the Rofi menu
options=("Extend Monitors
Duplicate Monitors")
choice=$(printf '%s

' "${options[@]}" | rofi -dmenu -i -p "Monitor configuration")

# Run the appropriate script
case $choice in
    "Extend Monitors")
        cp ~/.config/hypr/monitors_extend.conf ~/.config/hypr/monitors.conf
        clean
        ;;
    "Duplicate Monitors")
        cp ~/.config/hypr/monitors_duplicate.conf ~/.config/hypr/monitors.conf
        clean
        ;;
esac