#!/bin/bash

# Define the options for the Rofi menu
options=("Laptop Screen
Extend Monitors
Duplicate Monitors")
choice=$(printf '%s

' "${options[@]}" | rofi -dmenu -i -p "Monitor configuration")

# Run the appropriate script
case $choice in
"Laptop Screen")
    cp $HOME/.config/hypr/monitors/monitors_default.conf $HOME/.config/hypr/monitors.conf
    ;;
"Extend Monitors")
    cp $HOME/.config/hypr/monitors/monitors_extend.conf $HOME/.config/hypr/monitors.conf
    ;;
"Duplicate Monitors")
    cp $HOME/.config/hypr/monitors/monitors_duplicate.conf $HOME/.config/hypr/monitors.conf
    ;;
esac
reload-hyprland
