#!/usr/bin/env bash
$HOME/.config/waybar/scripts/launch # will reload hyprland also
# hyprctl reload
# restart portals
systemctl restart --user xdg-desktop-portal-hyprland
notify-send "Hyprland reloaded"
