[managers.system]
items = [
    "python3",
    "python-pip",
    "python-pipx",
    "pypy3",
    "mypy",
    "ruff",
    "uv",
    "python-termcolor",
    "python-lsprotocol",
    "python-mechanize",
]
