[managers.system]
items = [
    "python2-bin",
    "python3",
    "python-pip",
    "uv",
    "pypy3",
    "ruff",
    "uv",
    "python-termcolor",
    "python-lsprotocol",
    "python-mechanize",
]
