#!/bin/bash

/usr/bin/systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME
/usr/bin/dbus-update-activation-environment --systemd --all
# wait untils the systemd variables are set
while [ $(systemctl --user show-environment | grep -c DISPLAY) -eq 0 ]; do
    sleep 1
    notify-send "Waiting for systemd variables to be set"
done
systemctl --user start hyprland-session.target

# SIGNAL SYSTEMD SERVICES
# /usr/bin/systemctl --user start blueman-applet
# /usr/bin/systemctl --user start nm-applet
# /usr/bin/systemctl --user start udiskie
# /usr/bin/systemctl --user restart waybar-icons
