[managers.system]
items = [
    "nvidia-dkms", # or nvidia-open-dkms (if lucky)
    "libva-nvidia-driver",
    "nvidia-utils",
    "lib32-nvidia-utils",
    "nvidia-settings",
    "opencl-nvidia",
    "cuda",
    "cudnn",
    "cuda-tools",
    "nvenc",
]
