[managers.system]
items = [
    "nvidia-open-dkms", # or nvidia-dkms (if your your graphics card is not supported)
    "libva-nvidia-driver",
    "nvidia-utils",
    "lib32-nvidia-utils",
    "nvidia-settings",
    "opencl-nvidia",
    "cuda",
    "cudnn",
    "cuda-tools",
    "nvenc",
    "switcheroo-control",
]
