[managers.system]
items = [
    # use either nvidia-open-dkms or nvidia-dkms (if your your graphics card is not supported)
    "nvidia-dkms",
    "libva-nvidia-driver",
    "libva-utils",
    "nvidia-utils",
    "nvidia-settings",
    "opencl-nvidia",
    "cuda",
    "cudnn",
    "cuda-tools",
    # "nvenc",
    "switcheroo-control",
    "egl-wayland",
]
