# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "applications/password_manager",
    "programming/python/data_science",
]

[managers.system]
items = [
    "seadrive-gui",
    "ocrmypdf",
    "github-copilot-cli",
]

[managers.systemd-user]
items = [
    "seadrive",
]
