# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "asus",
    "gpu_drivers/intel",
    "gpu_drivers/nvidia",
    "hacking",
    "applications/password_manager",
    "programming/python/data_science",
]

[managers.system]
items = [
    "chaotic-aur/seadrive-gui"
]

[managers.systemd]
items = [
    "NetworkManager",
    "bluetooth"
]
