# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "asus",
    "gpu_drivers/intel",
    "gpu_drivers/nvidia",
    "hacking",
    "applications/password_manager",
    "programming/python/data_science",
]

[managers.system]
items = [
    "seadrive-gui",
    "ocrmypdf",
]

[managers.systemd-system]
items = [
    "NetworkManager",
    "bluetooth"
]

[managers.systemd-user]
items = [
    "seadrive",
]
