name: iso_build
on:
  workflow_dispatch:
  # schedule:
  #  - cron:  '30 2 * * *'

jobs:
  prepare-release:
    runs-on: self-hosted
    steps:
      - name: Allow workflow to be cancelled
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'DDMMYYYYHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
  build-release:
    runs-on: self-hosted
    needs: [prepare-release]
    permissions:
      contents: write
    container:
      image: ghcr.io/evangelospro/archbase:latest
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check dependencies
        run: |
          cd iso
          ./prep.sh
          # replace "exit $E_ROOT" with "#exit $E_ROOT" in /usr/bin/makepkg, only do this in a container not when building locally
          sed -i 's/exit $E_ROOT/#exit $E_ROOT/g' /usr/bin/makepkg
      - name: Build ISO
        run: |
          cd iso
          ./build.sh
      - name: List files
        run: |
          sudo chmod -R 777 ./iso/isoOUT
          ls -lasih ./iso/isoOUT
      - name: Upload Releases only if build was successful
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.outputs.release_tag }}
          files: |
            isoOUT/*.part*
            isoOUT/*.sha256
            isoOUT/*.txt
          fail_on_unmatched_files: true
